SELECT CASE WHEN(numero) IS NOT NULL
THEN
logradouro+ ', '+pais+' - '+CONVERT(VARCHAR(10),numero) 
ELSE
logradouro+', '+ pais
END AS end_completo
FROM fornecedor


SELECT SUBSTRING(cpf,1,3)+'.'+SUBSTRING(cpf,4,3)+'.'+SUBSTRING(cpf,5,3)+'-'+SUBSTRING(cpf,6,2) AS CPF,
SUBSTRING(rg,1,8)+'-'+SUBSTRING(rg,9,1) AS RG
C.LOGRADOURO+' '+CONVERT(VARCHAR(05),C.NUMERO) AS ENDERECO
FROM CLIENTES C INNER JOIN PEDIDO P 
ON P.RG_ClIENTE = C.RG
WHERE P.NOTAF = 1004


SELECT valor*0.10
FROM pedido
WHERE nota_fiscal = 1003

SELECT valor*0.05 
FROM PEDIDO 
WHERE nota_fiscal > 700

UPDATE MERCADORIA
SET PRECO = PRECO+(PRECO*0.2) 
WHERE QTD < 10

SELECT P.DAT,P.VALOR 
FROM PEDIDO P
INNER JOIN CLIENTES C ON C.RG = P.RG_ClIENTE
WHERE C.NOME LIKE '%Luiz%'



